stages:
  - build
  - test


build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/schehata/gitlab-pipeline-trigger .
    - docker push registry.gitlab.com/schehata/gitlab-pipeline-trigger

  
e2e:
  stage: test
  when: manual
  image: registry.gitlab.com/schehata/gitlab-pipeline-trigger
  script:
    - /trigger/main -a=$API_TOKEN -p=$PROJECT_ID -t=$TRIGGER_TOKEN -w=true